---
title: Ethanbrookins.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Hank Quinlan, Horrible Cop
markdown: kramdown
permalink: "/blog/:year/:month/:day/:title"
